
= FINPO API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head

//include::overview.adoc[]

&nbsp;

&nbsp;

&nbsp;


== 소셜 로그인

=== 인증

==== 토큰 재발급

Access token이 만료되었을 때 해당 방식으로 토큰을 재발급합니다

operation::reissue[snippets='http-request,request-fields,http-response,response-fields']

Refresh token이 발급된지 30일이 넘었다면 재발급이 불가합니다.

새로 로그인해주세요.

&nbsp;

&nbsp;

&nbsp;

==== 닉네임 중복 체크

가입한 유저의 경우 기존 닉네임으로 중복체크해도 false 뜨게 예외처리 해놨습니다.

operation::닉네임중복체크[snippets='http-request,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

//==== 이메일 중복 체크
//
//가입한 유저의 경우 기존 이메일로 중복체크해도 false 뜨게 예외처리 해놨습니다.
//
//operation::이메일중복체크[snippets='http-request,request-parameters,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;


=== 카카오

==== 로그인
operation::kakao-login-success[snippets='http-request,request-headers']
&nbsp;

**성공 시**

operation::kakao-login-success[snippets='http-response,response-fields']

&nbsp;
&nbsp;

**실패 시**

각 소셜 아이디로부터 얻어온 데이터를 가능한 return 해드립니다.

HTTP status는 202(Accepted) 입니다.

operation::kakao-login-fail[snippets='http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 회원가입

**multipart/form-data 형식으로 보내주세요**


operation::kakao-register[snippets='http-request,request-headers,request-parameters,request-parts']

&nbsp;

&nbsp;

operation::kakao-register[snippets='http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;



=== 구글

*id_token* 말고 *access_token* 을 주셔야 생년월일, 성별도 받아올 수 있습니다.

==== 로그인
operation::구글로그인성공[snippets='http-request,request-headers']
&nbsp;

**성공 시**

operation::구글로그인성공[snippets='http-response,response-fields']

&nbsp;
&nbsp;

**실패 시**

각 소셜 아이디로부터 얻어온 데이터를 가능한 return 해드립니다.

HTTP status는 202(Accepted) 입니다.

operation::구글로그인실패[snippets='http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 회원가입

**multipart/form-data 형식으로 보내주세요**


operation::구글회원가입[snippets='http-request,request-headers,request-parameters,request-parts']

&nbsp;

&nbsp;

operation::구글회원가입[snippets='http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;



=== 애플

==== 로그인
operation::애플로그인성공[snippets='http-request,request-headers']
&nbsp;

**성공 시**

operation::애플로그인성공[snippets='http-response,response-fields']

&nbsp;
&nbsp;

**실패 시**

애플 로그인은 가져올 수 있는 정보가 이메일밖에 없습니다.

HTTP status는 202(Accepted) 입니다.

operation::애플로그인실패[snippets='http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 회원가입

**multipart/form-data 형식으로 보내주세요**


operation::애플회원가입[snippets='http-request,request-headers,request-parameters,request-parts']

&nbsp;

&nbsp;

operation::애플회원가입[snippets='http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


== 회원
=== 현재 상태 및 이용 목적
==== 현재 상태 목록 조회
operation::유저상태목록조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 이용 목적 목록 조회
operation::이용목적목록조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 등록 및 수정

등록 시에는 statusId, purposeIds 다 보내주세요.

수정 시에는 수정할 속성만(둘 중 하나만) 보내주셔도 됩니디.

operation::현재상태이용목적추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 내 이용 목적 조회

operation::내이용목적조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 내 정보
==== 조회
operation::내정보조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정

*프로필 이미지 변경은 이 API로 불가능합니다*

operation::내정보변경[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 프로필 이미지 변경

operation::프로필이미지업데이트[snippets='http-request,request-headers,request-parts,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 탈퇴

구글 회원일 시 access_token을, 애플 회원일 시 code를 body에 넣어 보내주세요.

operation::회원탈퇴[snippets='http-request,request-fields,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== OAuth 연결 해제 후 탈퇴
operation::회원탈퇴예외[snippets='http-response']

&nbsp;

&nbsp;

&nbsp;


==== 정지 내역 조회

정지된 상태에서 커뮤니티 api `/post` `/comment` 조회 시 403 Forbidden을 응답합니다.

    {
      "sub": "23786",
      "nickname": "sadfsad",
      ...
      "auth": "ROLE_BANNED_USER",
    }

또한 위처럼 access token 파싱하여 auth가 ROLE_BANNED_USER라면 정지된 상태입니다.

operation::내정지내역조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 차단한 유저 조회

실명으로 작성한 유저만 조회 가능합니다

operation::차단한유저조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 차단한 유저 해제

operation::차단한유저해제[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;



== 지역
=== 이름 조회
==== 지역이름
operation::region1[snippets='http-request,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 상세 지역이름 (부모지역 id)
operation::region2-busan[snippets='http-request,request-parameters,http-response,response-fields']
&nbsp;

&nbsp;

&nbsp;

==== 상세 지역이름 (전체)
operation::자식지역조회[snippets='http-request,request-parameters,http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

=== 나의 거주지역
==== 조회
operation::get-my-default-region[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정
operation::update-my-default-region[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 나의 관심지역
==== 조회 (거주지역 포함)
operation::get-my-regions[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정

기존 관심지역은 삭제되고 요청주신 지역id들이 관심지역으로 등록됩니다.

관심지역(거주지역 X) id들만 보내주세요.

서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?

operation::update-my-interest-region[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


//==== 추가
//
//서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?
//
//operation::insert-my-interest-region[snippets='http-request,request-headers,request-fields,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;
//
//
//==== 삭제
//operation::관심지역들삭제[snippets='http-request,request-headers,request-parameters,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;








== 카테고리
=== 카테고리 조회
==== child 형식 카테고리
operation::child형식카테고리조회[snippets='http-request,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 상위 카테고리
operation::1차카테고리조회[snippets='http-request,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 하위 카테고리 (상위 카테고리 자식)
operation::자식카테고리조회[snippets='http-request,request-parameters,http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 하위 카테고리 (전체)
operation::2차카테고리조회[snippets='http-request,request-parameters,http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

=== 나의 관심카테고리
==== 조회
operation::내관심카테고리[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 부모 카테고리만 조회
operation::내관심카테고리부모[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정

기존 관심카테고리는 삭제되고 요청주신 카테고리id들이 관심카테고리로 등록됩니다.

서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?

operation::내관심카테고리수정[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


//==== 추가
//
//서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?
//
//operation::내관심카테고리추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;
//
//
//==== 삭제
//operation::내관심카테고리삭제[snippets='http-request,request-headers,request-parameters,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;


== 알림

=== 내 알림

==== 조회

operation::내알림조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 전체 알림 받기

operation::알림받기[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 전체 알림 끄기

operation::알림끊기[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 알림 수정

operation::알림수정[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 기록
==== 내 알림 기록 조회

operation::내알림기록조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 내 알림기록 최신순 조회 (무한스크롤)

`page=0&sort=id,desc` 으로 고정하고 `lastId` 만 갱신해서 요청 주세요

operation::내알림기록최신순조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 내 알림 기록 삭제

operation::내알림기록삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== FCM 형식

==== 정책
    data:
        category: "일자리 진로"
        id: "5343"
        region: "서울 마포"
        title: "마포구 뭐시기머시기"
        type: "POLICY"
    fcmMessageId: "bc252c00-bf36-46e3-b051-ac7c2d92dd25"
    from: "612456786880"
    priority: "normal"

==== 댓글

댓글 100자 넘어갈 시 100자까지 보여주고 뒤에 ... 붙음

    data:
        content: "댓글댓글대대대대 개대ㅐㄷ슥"
        id: "5345"
        postContent:"글내용내용내용"
        postId: "5333"
        type: "COMMENT"
    fcmMessageId: "60301125-b076-4809-8168-8efac06ae4fa"
    from: "612456786880"
    priority: "normal"


==== 대댓글

    data:
        content: "대댓글글글  ㄹㄴㄹㅇㄴㄹㅇㅁ너"
        id: "5348"
        postContent:"글내용내용내용"
        postId: "5309"
        type: "CHILDCOMMENT"
    fcmMessageId: "cc503903-15da-4819-956e-27cd6ba8c7c7"
    from: "612456786880"
    priority: "normal"

&nbsp;

&nbsp;

&nbsp;

== 정책
=== 상세 정보
==== 조회

operation::정책상세조회[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 나의 정책
==== 조회

저장되어 있는 관심+기본지역, 관심정책 카테고리에 해당하는 정책들을 조회합니다.

operation::내맞춤정책조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 검색

==== 예시 (제목으로 검색)

operation::정책제목검색[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 예시 (시작날짜로 검색)

operation::정책날짜검색[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 정렬

==== 예시 (인기순으로 정렬)

operation::정책인기순검색[snippets='http-request,request-headers,http-response']

&nbsp;

&nbsp;

&nbsp;


=== 나의 관심정책
==== 조회

operation::내관심정책조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 추가

policyId가 중복된다면 data에 null을 반환합니다.

최대 개수는 20개입니다.

operation::내관심정책추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 관심정책 id로 삭제

operation::내관심정책삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 정책 id로 삭제

operation::내관심정책삭제정책id[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 나의 참여정책
==== 조회

operation::내참여정책조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 추가

메모 최대 글자 수는 200자 입니다.

policyId가 중복된다면 data에 null을 반환합니다.

최대 개수는 20개입니다.

operation::내참여정책추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 수정

메모 최대 글자 수는 200자 입니다.

operation::내참여정책수정[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 참여정책 id로 삭제

operation::내참여정책삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 정책 id로 삭제

operation::내참여정책삭제정책id[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

= 커뮤니티
== 게시글
=== 조회
==== 상세 조회

operation::글상세조회[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 최신순 조회 (무한스크롤)

`page=0&sort=id,desc` 으로 고정하고 `lastId` 만 갱신해서 요청 주세요

operation::글최신순조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 전체 조회/검색

operation::글조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 내가 쓴 글 조회

operation::내글조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 북마크한 글 조회

operation::내북마크글조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 좋아요한 글 조회

operation::내좋아요한글조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 댓글단 글 조회

operation::내댓글단글조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 작성

==== 이미지 첨부

operation::글이미지업로드[snippets='http-request,request-headers,request-parts,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 글 작성

먼저 이미지 첨부 request를 보낸 후, imgs에 img url을 넣어주세요

이미지는 5개 이하여야 입니다.

최대 글자 수는 1000자 입니다.

operation::글쓰기[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 익명 글 작성

먼저 이미지 첨부 request를 보낸 후, imgs에 img url을 넣어주세요

이미지는 5개 이하여야 입니다.

최대 글자 수는 1000자 입니다.

operation::글쓰기익명[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 글 수정

먼저 이미지 첨부 request를 보낸 후, imgs에 img url을 넣어주세요

최대 글자 수는 1000자 입니다.

operation::글수정[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 글 삭제

operation::글삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 좋아요
==== 추가

operation::글좋아요[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 취소

operation::글좋아요취소[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 북마크
==== 추가

operation::글북마크[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 취소

operation::글북마크취소[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 차단
==== 게시글 작성 유저 차단

operation::글작성유저차단[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

== 댓글

=== 조회

==== 게시글 댓글 조회

operation::글댓글조회[snippets='http-request,request-headers,path-parameters,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 작성

==== 댓글 작성

최대 글자 수는 200자 입니다.

operation::댓글쓰기[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;r

&nbsp;

&nbsp;

==== 내가 익명으로 쓴 글에 익명 댓글 작성 시

글 작성자이므로 익명id를 주지 않고 isWriter를 true로 줍니다.

operation::댓글쓰기익명[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 대댓글 작성

최대 글자 수는 200자 입니다.

operation::대댓글쓰기[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 댓글 수정

최대 글자 수는 200자 입니다.

operation::댓글수정[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 댓글 삭제

operation::댓글삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 차단
==== 댓글 작성 유저 차단

operation::댓글작성유저차단[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

== 신고

=== 신고 사유

==== 신고 사유 조회

operation::신고사유조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 댓글
==== 댓글 신고

operation::댓글신고[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 게시글
==== 게시글 신고

operation::글신고[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

== 정보
==== OPEN API

[source,http,options="nowrap"]
----
GET /information/open-api HTTP/1.1
Content-Type: application/json;charset=UTF-8
Host: dev.finpo.kr
----
[source,options="nowrap"]
----
{
  "success":true,
  "errorCode":0,
  "message":"Ok",
  "data":[
    {
      "id":11827,
      "type":"open-api",
      "content":"한국고용정보원 온라인청년센터",
      "url":"https://www.youthcenter.go.kr/opi/openApiIntro.do",
      "status":null,
      "hidden":false
    },
    {
      "id":11828,
      "type":"open-api",
      "content":"경기데이터드림",
      "url":"https://data.gg.go.kr/portal/intro/develop/searchBulletinPage.do",
      "status":null,
      "hidden":false
    }
  ]
}
----

&nbsp;

&nbsp;

&nbsp;

==== 서버 상태

[source,http,options="nowrap"]
----
GET /information/server HTTP/1.1
Content-Type: application/json;charset=UTF-8
Host: dev.finpo.kr
----
[source,options="nowrap"]
----
{
  "success":true,
  "errorCode":0,
  "message":"Ok",
  "data":[
    {
      "id":11829,
      "type":"server",
      "content":"점검중\n(`22.07.18 23:00 ~ `22.07.19 02:00)",
      "url":null,
      "status":false,
      "hidden":false
    }
  ]
}
----
