
= FINPO API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head

//include::overview.adoc[]

&nbsp;

&nbsp;

&nbsp;


== 소셜 로그인

=== 인증

==== 토큰 재발급

Access token이 만료되었을 때 해당 방식으로 토큰을 재발급합니다

operation::reissue[snippets='http-request,request-fields,http-response,response-fields']

Refresh token이 발급된지 30일이 넘었다면 재발급이 불가합니다.

새로 로그인해주세요.

&nbsp;

&nbsp;

&nbsp;

==== 닉네임 중복 체크

가입한 유저의 경우 기존 닉네임으로 중복체크해도 false 뜨게 예외처리 해놨습니다.

operation::닉네임중복체크[snippets='http-request,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

//==== 이메일 중복 체크
//
//가입한 유저의 경우 기존 이메일로 중복체크해도 false 뜨게 예외처리 해놨습니다.
//
//operation::이메일중복체크[snippets='http-request,request-parameters,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;


=== 카카오

==== 로그인
operation::kakao-login-success[snippets='http-request,request-headers']
&nbsp;

**성공 시**

operation::kakao-login-success[snippets='http-response,response-fields']

&nbsp;
&nbsp;

**실패 시**

각 소셜 아이디로부터 얻어온 데이터를 가능한 return 해드립니다.

HTTP status는 202(Accepted) 입니다.

operation::kakao-login-fail[snippets='http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 회원가입

**multipart/form-data 형식으로 보내주세요**


operation::kakao-register[snippets='http-request,request-headers,request-parameters,request-parts']

&nbsp;

&nbsp;

operation::kakao-register[snippets='http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;



=== 구글

*id_token* 말고 *access_token* 을 주셔야 생년월일, 성별도 받아올 수 있습니다.

==== 로그인
operation::구글로그인성공[snippets='http-request,request-headers']
&nbsp;

**성공 시**

operation::구글로그인성공[snippets='http-response,response-fields']

&nbsp;
&nbsp;

**실패 시**

각 소셜 아이디로부터 얻어온 데이터를 가능한 return 해드립니다.

HTTP status는 202(Accepted) 입니다.

operation::구글로그인실패[snippets='http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 회원가입

**multipart/form-data 형식으로 보내주세요**


operation::구글회원가입[snippets='http-request,request-headers,request-parameters,request-parts']

&nbsp;

&nbsp;

operation::구글회원가입[snippets='http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;



=== 애플

==== 로그인
operation::애플로그인성공[snippets='http-request,request-headers']
&nbsp;

**성공 시**

operation::애플로그인성공[snippets='http-response,response-fields']

&nbsp;
&nbsp;

**실패 시**

애플 로그인은 가져올 수 있는 정보가 이메일밖에 없습니다.

HTTP status는 202(Accepted) 입니다.

operation::애플로그인실패[snippets='http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 회원가입

**multipart/form-data 형식으로 보내주세요**


operation::애플회원가입[snippets='http-request,request-headers,request-parameters,request-parts']

&nbsp;

&nbsp;

operation::애플회원가입[snippets='http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


== 회원
=== 현재 상태 및 이용 목적
==== 현재 상태 목록 조회
operation::유저상태목록조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 이용 목적 목록 조회
operation::이용목적목록조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 등록
operation::현재상태이용목적추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 내 정보
==== 조회
operation::내정보조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정

*프로필 이미지 변경은 이 API로 불가능합니다*

operation::내정보변경[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 프로필 이미지 변경

operation::프로필이미지업데이트[snippets='http-request,request-headers,request-parts,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 탈퇴

구글 회원일 시 access_token을 body에 넣어 보내주세요.

operation::회원탈퇴[snippets='http-request,request-fields,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== OAuth 연결 해제 후 탈퇴
operation::회원탈퇴예외[snippets='http-response']


&nbsp;

&nbsp;

&nbsp;








== 지역
=== 이름 조회
==== 지역이름
operation::region1[snippets='http-request,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 상세 지역이름 (부모지역 id)
operation::region2-busan[snippets='http-request,request-parameters,http-response,response-fields']
&nbsp;

&nbsp;

&nbsp;

==== 상세 지역이름 (전체)
operation::자식지역조회[snippets='http-request,request-parameters,http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

=== 나의 거주지역
==== 조회
operation::get-my-default-region[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정
operation::update-my-default-region[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 나의 관심지역
==== 조회 (거주지역 포함)
operation::get-my-regions[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정

기존 관심지역은 삭제되고 요청주신 지역id들이 관심지역으로 등록됩니다.

관심지역(거주지역 X) id들만 보내주세요.

서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?

operation::update-my-interest-region[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


//==== 추가
//
//서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?
//
//operation::insert-my-interest-region[snippets='http-request,request-headers,request-fields,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;
//
//
//==== 삭제
//operation::관심지역들삭제[snippets='http-request,request-headers,request-parameters,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;








== 카테고리
=== 카테고리 조회
==== child 형식 카테고리
operation::child형식카테고리조회[snippets='http-request,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 상위 카테고리
operation::1차카테고리조회[snippets='http-request,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 하위 카테고리 (상위 카테고리 자식)
operation::자식카테고리조회[snippets='http-request,request-parameters,http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

==== 하위 카테고리 (전체)
operation::2차카테고리조회[snippets='http-request,request-parameters,http-response,response-fields']


&nbsp;

&nbsp;

&nbsp;

=== 나의 관심카테고리
==== 조회
operation::내관심카테고리[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 수정

기존 관심카테고리는 삭제되고 요청주신 카테고리id들이 관심카테고리로 등록됩니다.

서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?

operation::내관심카테고리수정[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


//==== 추가
//
//서버에서 중복체크 하지만, 중복이 안오는게 베스트겠죠?
//
//operation::내관심카테고리추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;
//
//
//==== 삭제
//operation::내관심카테고리삭제[snippets='http-request,request-headers,request-parameters,http-response,response-fields']
//
//&nbsp;
//
//&nbsp;
//
//&nbsp;


== 정책
=== 상세 정보
==== 조회

operation::정책상세조회[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


=== 나의 정책
==== 조회

저장되어 있는 관심+기본지역, 관심정책 카테고리에 해당하는 정책들을 조회합니다.

operation::내맞춤정책조회[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 검색

==== 예시 (제목으로 검색)

operation::정책제목검색[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 예시 (시작날짜로 검색)

operation::정책날짜검색[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 정렬

==== 예시 (인기순으로 정렬)

operation::정책인기순검색[snippets='http-request,request-headers,http-response']

&nbsp;

&nbsp;

&nbsp;


=== 나의 관심정책
==== 조회

operation::내관심정책조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 추가

operation::내관심정책추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;


==== 삭제

operation::내관심정책삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

=== 나의 참여정책
==== 조회

operation::내참여정책조회[snippets='http-request,request-headers,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 추가

operation::내참여정책추가[snippets='http-request,request-headers,request-fields,http-response,response-fields']
&nbsp;

참여정책을 추가하였는데 응답의 countOfInterest는 1이 증가되어 반환되지 않습니다.
&nbsp;

db 쿼리 실행 시간의 문제로 추측되는데, 다시 api로 조회하시면 1 증가한 것을 확인하실 수 있습니다.

&nbsp;

&nbsp;

&nbsp;


==== 수정

operation::내참여정책수정[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;

==== 삭제

operation::내참여정책삭제[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

&nbsp;

&nbsp;

&nbsp;